# -*- coding: utf-8 -*-

"""
Anki Add-on: Code Syntax Highlighter

Entry point for the add-on into Anki 2.0.x

Please do not edit this file if you are not sure what you are doing.

Copyright: (c) 2018 Glutanimate <https://glutanimate.com/>
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl.html>
"""

import syntax_highlighter.main